//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace MyFirstApp.Data
{
    public class Employee
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }

    }
}